export interface Cafe {
  id: number
  slug: string
  name: string
  name_ja: string
  category: string
  city: string
  address: string
  description: string
  price_range: number
  photos: string[]
  google_maps_url: string
  opening_days: boolean[]
  feature_ids: number[]
  koi_number: number
  super_koi_number: number
  review_ids: number[]
  latitude: number
  longitude: number
  created_at: Date
}

export const cafes: Cafe[] = [
// ===== OCHAYA (3 premiers) =====
{
  id: 1,
  slug: 'ippodo-tea-kyoto',
  name: 'Ippodo Tea',
  name_ja: '一保堂茶舗',
  category: 'ochaya',
  city: 'Kyoto',
  address: 'Teramachi-dori, Nakagyo-ku',
  description: 'Maison de thé historique fondée en 1717, spécialiste du thé vert premium',
  price_range: 2,
  photos: ['/images/cafes/00001b.jpg', '/images/cafes/00001m.jpg', '/images/cafes/00001g1.jpg', '/images/cafes/00001g2.jpg', '/images/cafes/00001g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/ippodo',
  opening_days: [true, true, false, true, true, true, true],
  feature_ids: [1, 3, 5],
  koi_number: 342,
  super_koi_number: 87,
  review_ids: [21, 45],
  latitude: 35.0116,
  longitude: 135.7681,
  created_at: new Date('2024-01-01')
},
{
  id: 2,
  slug: 'tsujiri-gion',
  name: 'Tsujiri Gion',
  name_ja: '辻利 祇園',
  category: 'ochaya',
  city: 'Kyoto',
  address: 'Gion, Higashiyama-ku',
  description: 'Salon de thé emblématique de Gion, célèbre pour ses parfaits au matcha',
  price_range: 2,
  photos: ['/images/cafes/00002b.jpg', '/images/cafes/00002m.jpg', '/images/cafes/00002g1.jpg', '/images/cafes/00002g2.jpg', '/images/cafes/00002g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/tsujiri',
  opening_days: [true, true, true, true, true, true, true],
  feature_ids: [1, 2, 5, 8],
  koi_number: 521,
  super_koi_number: 143,
  review_ids: [32, 78, 156],
  latitude: 35.0036,
  longitude: 135.7789,
  created_at: new Date('2024-01-02')
},
{
  id: 3,
  slug: 'nakamura-tokichi-uji',
  name: 'Nakamura Tokichi',
  name_ja: '中村藤吉',
  category: 'ochaya',
  city: 'Uji',
  address: 'Uji-shi, Kyoto',
  description: 'Maison de thé centenaire dans la capitale du thé vert japonais',
  price_range: 3,
  photos: ['/images/cafes/00003b.jpg', '/images/cafes/00003m.jpg', '/images/cafes/00003g1.jpg', '/images/cafes/00003g2.jpg', '/images/cafes/00003g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/nakamura',
  opening_days: [true, true, true, false, true, true, true],
  feature_ids: [3, 5, 6],
  koi_number: 689,
  super_koi_number: 201,
  review_ids: [12, 89, 234],
  latitude: 34.8842,
  longitude: 135.8008,
  created_at: new Date('2024-01-03')
},

// ===== KISSATEN (3 premiers) =====
{
  id: 16,
  slug: 'chatei-hatou',
  name: 'Chatei Hatou',
  name_ja: '茶亭羽當',
  category: 'kissaten',
  city: 'Tokyo',
  address: 'Jingumae, Shibuya-ku',
  description: 'Kissaten emblématique de Shibuya depuis 1989, café siphon légendaire',
  price_range: 2,
  photos: ['/images/cafes/00016b.jpg', '/images/cafes/00016m.jpg', '/images/cafes/00016g1.jpg', '/images/cafes/00016g2.jpg', '/images/cafes/00016g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/chateihatou',
  opening_days: [true, true, false, true, true, true, false],
  feature_ids: [1, 3, 6],
  koi_number: 892,
  super_koi_number: 245,
  review_ids: [23, 156, 543],
  latitude: 35.6695,
  longitude: 139.7075,
  created_at: new Date('2024-01-16')
},
{
  id: 17,
  slug: 'cafe-de-lambre',
  name: 'Cafe de l\'Ambre',
  name_ja: 'カフェ・ド・ランブル',
  category: 'kissaten',
  city: 'Tokyo',
  address: 'Ginza, Chuo-ku',
  description: 'Institution historique de Ginza fondée en 1948, temple du café vieilli',
  price_range: 3,
  photos: ['/images/cafes/00017b.jpg', '/images/cafes/00017m.jpg', '/images/cafes/00017g1.jpg', '/images/cafes/00017g2.jpg', '/images/cafes/00017g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/lambre',
  opening_days: [false, true, true, true, true, true, true],
  feature_ids: [3, 5, 6],
  koi_number: 1234,
  super_koi_number: 412,
  review_ids: [34, 234, 789],
  latitude: 35.6719,
  longitude: 139.7648,
  created_at: new Date('2024-01-17')
},
{
  id: 18,
  slug: 'cafe-bach',
  name: 'Cafe Bach',
  name_ja: 'カフェ・バッハ',
  category: 'kissaten',
  city: 'Tokyo',
  address: 'Taito-ku',
  description: 'Kissaten de renommée mondiale, maître torréfacteur depuis 1968',
  price_range: 2,
  photos: ['/images/cafes/00018b.jpg', '/images/cafes/00018m.jpg', '/images/cafes/00018g1.jpg', '/images/cafes/00018g2.jpg', '/images/cafes/00018g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/bach',
  opening_days: [true, true, true, false, true, true, true],
  feature_ids: [1, 3, 5],
  koi_number: 1045,
  super_koi_number: 328,
  review_ids: [45, 267, 891],
  latitude: 35.7219,
  longitude: 139.7965,
  created_at: new Date('2024-01-18')
},

// ===== JUNSEIKISSATEN (3 premiers) =====
{
  id: 31,
  slug: 'takachiho-jingumae',
  name: 'Takachiho',
  name_ja: '高千穂',
  category: 'junseikissaten',
  city: 'Tokyo',
  address: 'Jingumae, Shibuya-ku',
  description: 'Pure kissaten silencieux, café siphon et méditation',
  price_range: 2,
  photos: ['/images/cafes/00031b.jpg', '/images/cafes/00031m.jpg', '/images/cafes/00031g1.jpg', '/images/cafes/00031g2.jpg', '/images/cafes/00031g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/takachiho',
  opening_days: [true, true, false, true, true, true, false],
  feature_ids: [3, 5],
  koi_number: 678,
  super_koi_number: 189,
  review_ids: [34, 234, 567],
  latitude: 35.6702,
  longitude: 139.7065,
  created_at: new Date('2024-01-31')
},
{
  id: 32,
  slug: 'sabouru-jimbocho',
  name: 'Sabouru',
  name_ja: 'さぼうる',
  category: 'junseikissaten',
  city: 'Tokyo',
  address: 'Jimbocho, Chiyoda-ku',
  description: 'Institution de Jimbocho depuis 1955, ambiance studieuse garantie',
  price_range: 1,
  photos: ['/images/cafes/00032b.jpg', '/images/cafes/00032m.jpg', '/images/cafes/00032g1.jpg', '/images/cafes/00032g2.jpg', '/images/cafes/00032g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/sabouru',
  opening_days: [false, true, true, true, true, true, true],
  feature_ids: [1, 3, 6],
  koi_number: 1123,
  super_koi_number: 345,
  review_ids: [45, 289, 765],
  latitude: 35.6958,
  longitude: 139.7573,
  created_at: new Date('2024-02-01')
},
{
  id: 33,
  slug: 'tsubakiya-kanda',
  name: 'Tsubakiya',
  name_ja: '椿屋珈琲店',
  category: 'junseikissaten',
  city: 'Tokyo',
  address: 'Kanda, Chiyoda-ku',
  description: 'Pure kissaten avec décor Taisho romantique',
  price_range: 2,
  photos: ['/images/cafes/00033b.jpg', '/images/cafes/00033m.jpg', '/images/cafes/00033g1.jpg', '/images/cafes/00033g2.jpg', '/images/cafes/00033g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/tsubakiya',
  opening_days: [true, true, true, true, true, true, false],
  feature_ids: [3, 5, 6],
  koi_number: 834,
  super_koi_number: 221,
  review_ids: [67, 345],
  latitude: 35.6918,
  longitude: 139.7708,
  created_at: new Date('2024-02-02')
},

// ===== BOOK CAFE (3 premiers) =====
{
  id: 46,
  slug: 'tsutaya-daikanyama',
  name: 'Tsutaya Books Daikanyama',
  name_ja: '蔦屋書店 代官山',
  category: 'book-cafe',
  city: 'Tokyo',
  address: 'Daikanyama, Shibuya-ku',
  description: 'Librairie-café emblématique, temple du design et de la culture',
  price_range: 3,
  photos: ['/images/cafes/00046b.jpg', '/images/cafes/00046m.jpg', '/images/cafes/00046g1.jpg', '/images/cafes/00046g2.jpg', '/images/cafes/00046g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/tsutaya',
  opening_days: [true, true, true, true, true, true, true],
  feature_ids: [1, 2, 4, 5, 7],
  koi_number: 1456,
  super_koi_number: 423,
  review_ids: [34, 267, 891],
  latitude: 35.6497,
  longitude: 139.7048,
  created_at: new Date('2024-02-15')
},
{
  id: 47,
  slug: 'book-and-bed-tokyo',
  name: 'Book and Bed Tokyo',
  name_ja: 'ブックアンドベッド東京',
  category: 'book-cafe',
  city: 'Tokyo',
  address: 'Ikebukuro, Toshima-ku',
  description: 'Concept unique de librairie-café avec lits capsules pour lecteurs',
  price_range: 2,
  photos: ['/images/cafes/00047b.jpg', '/images/cafes/00047m.jpg', '/images/cafes/00047g1.jpg', '/images/cafes/00047g2.jpg', '/images/cafes/00047g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/bookandbed',
  opening_days: [true, true, true, true, true, true, true],
  feature_ids: [1, 4, 5, 7],
  koi_number: 1234,
  super_koi_number: 378,
  review_ids: [45, 289, 654],
  latitude: 35.7295,
  longitude: 139.7109,
  created_at: new Date('2024-02-16')
},
{
  id: 48,
  slug: 'shibuya-publishing-booksellers',
  name: 'Shibuya Publishing & Booksellers',
  name_ja: '渋谷パブリッシング＆ブックセラーズ',
  category: 'book-cafe',
  city: 'Tokyo',
  address: 'Kamiyamacho, Shibuya-ku',
  description: 'Librairie-café indépendante spécialisée en culture et art',
  price_range: 2,
  photos: ['/images/cafes/00048b.jpg', '/images/cafes/00048m.jpg', '/images/cafes/00048g1.jpg', '/images/cafes/00048g2.jpg', '/images/cafes/00048g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/spbs',
  opening_days: [false, true, true, true, true, true, true],
  feature_ids: [1, 4, 5],
  koi_number: 789,
  super_koi_number: 234,
  review_ids: [67, 345],
  latitude: 35.6645,
  longitude: 139.6934,
  created_at: new Date('2024-02-17')
},

// ===== THIRD WAVE (3 premiers) =====
{
  id: 61,
  slug: 'onibus-coffee-nakameguro',
  name: 'Onibus Coffee',
  name_ja: 'オニバスコーヒー',
  category: 'third-wave',
  city: 'Tokyo',
  address: 'Nakameguro, Meguro-ku',
  description: 'Torréfacteur third wave pionnier de Tokyo, café de spécialité',
  price_range: 2,
  photos: ['/images/cafes/00061b.jpg', '/images/cafes/00061m.jpg', '/images/cafes/00061g1.jpg', '/images/cafes/00061g2.jpg', '/images/cafes/00061g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/onibus',
  opening_days: [true, true, true, true, true, true, true],
  feature_ids: [1, 4, 5, 7],
  koi_number: 1234,
  super_koi_number: 389,
  review_ids: [45, 234, 765],
  latitude: 35.6440,
  longitude: 139.6989,
  created_at: new Date('2024-03-02')
},
{
  id: 62,
  slug: 'about-life-coffee-brewers',
  name: 'About Life Coffee Brewers',
  name_ja: 'アバウトライフコーヒーブリュワーズ',
  category: 'third-wave',
  city: 'Tokyo',
  address: 'Shibuya, Shibuya-ku',
  description: 'Café third wave minimaliste, focus absolu sur la qualité',
  price_range: 2,
  photos: ['/images/cafes/00062b.jpg', '/images/cafes/00062m.jpg', '/images/cafes/00062g1.jpg', '/images/cafes/00062g2.jpg', '/images/cafes/00062g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/aboutlife',
  opening_days: [false, true, true, true, true, true, true],
  feature_ids: [1, 4, 5],
  koi_number: 923,
  super_koi_number: 267,
  review_ids: [67, 345, 891],
  latitude: 35.6605,
  longitude: 139.7012,
  created_at: new Date('2024-03-03')
},
{
  id: 63,
  slug: 'bear-pond-espresso',
  name: 'Bear Pond Espresso',
  name_ja: 'ベアポンドエスプレッソ',
  category: 'third-wave',
  city: 'Tokyo',
  address: 'Kitazawa, Setagaya-ku',
  description: 'Temple de l\'espresso artisanal, barista légendaire',
  price_range: 2,
  photos: ['/images/cafes/00063b.jpg', '/images/cafes/00063m.jpg', '/images/cafes/00063g1.jpg', '/images/cafes/00063g2.jpg', '/images/cafes/00063g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/bearpond',
  opening_days: [true, true, false, true, true, true, true],
  feature_ids: [4, 5],
  koi_number: 1456,
  super_koi_number: 456,
  review_ids: [78, 289, 654],
  latitude: 35.6614,
  longitude: 139.6682,
  created_at: new Date('2024-03-04')
},

// ===== COFFEE STAND (3 premiers) =====
{
  id: 76,
  slug: 'little-nap-coffee-yoyogi',
  name: 'Little Nap Coffee Stand',
  name_ja: 'リトルナップコーヒースタンド',
  category: 'coffee-stand',
  city: 'Tokyo',
  address: 'Yoyogi, Shibuya-ku',
  description: 'Micro coffee stand culte de Yoyogi, ambiance vintage',
  price_range: 1,
  photos: ['/images/cafes/00076b.jpg', '/images/cafes/00076m.jpg', '/images/cafes/00076g1.jpg', '/images/cafes/00076g2.jpg', '/images/cafes/00076g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/littlenap',
  opening_days: [true, true, false, true, true, true, true],
  feature_ids: [5, 7],
  koi_number: 1345,
  super_koi_number: 412,
  review_ids: [56, 289, 765],
  latitude: 35.6761,
  longitude: 139.7020,
  created_at: new Date('2024-03-17')
},
{
  id: 77,
  slug: 'toranomon-koffee',
  name: 'Toranomon Koffee',
  name_ja: '虎ノ門コーヒー',
  category: 'coffee-stand',
  city: 'Tokyo',
  address: 'Toranomon, Minato-ku',
  description: 'Coffee stand minimaliste pour businessmen pressés',
  price_range: 1,
  photos: ['/images/cafes/00077b.jpg', '/images/cafes/00077m.jpg', '/images/cafes/00077g1.jpg', '/images/cafes/00077g2.jpg', '/images/cafes/00077g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/toranomon',
  opening_days: [false, true, true, true, true, true, false],
  feature_ids: [5, 7],
  koi_number: 623,
  super_koi_number: 145,
  review_ids: [34, 178],
  latitude: 35.6684,
  longitude: 139.7474,
  created_at: new Date('2024-03-18')
},
{
  id: 78,
  slug: 'koffee-mameya-kakeru',
  name: 'Koffee Mameya Kakeru',
  name_ja: 'コーヒーマメヤカケル',
  category: 'coffee-stand',
  city: 'Tokyo',
  address: 'Jingumae, Shibuya-ku',
  description: 'Coffee stand haut de gamme, café à emporter premium',
  price_range: 2,
  photos: ['/images/cafes/00078b.jpg', '/images/cafes/00078m.jpg', '/images/cafes/00078g1.jpg', '/images/cafes/00078g2.jpg', '/images/cafes/00078g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/kakeru',
  opening_days: [true, true, true, false, true, true, true],
  feature_ids: [5, 7],
  koi_number: 934,
  super_koi_number: 278,
  review_ids: [67, 345, 678],
  latitude: 35.6702,
  longitude: 139.7075,
  created_at: new Date('2024-03-19')
},

// ===== ONSEN CAFE (3 premiers) =====
{
  id: 91,
  slug: 'onsen-ryokan-yuen-shinjuku',
  name: 'Onsen Ryokan Yuen Shinjuku',
  name_ja: '温泉旅館由縁新宿',
  category: 'onsen-cafe',
  city: 'Tokyo',
  address: 'Shinjuku, Shinjuku-ku',
  description: 'Onsen urbain avec salon de thé traditionnel, détente complète',
  price_range: 3,
  photos: ['/images/cafes/00091b.jpg', '/images/cafes/00091m.jpg', '/images/cafes/00091g1.jpg', '/images/cafes/00091g2.jpg', '/images/cafes/00091g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/yuen',
  opening_days: [true, true, true, true, true, true, true],
  feature_ids: [1, 3, 5, 10],
  koi_number: 1234,
  super_koi_number: 378,
  review_ids: [56, 289, 765],
  latitude: 35.6938,
  longitude: 139.7036,
  created_at: new Date('2024-04-01')
},
{
  id: 92,
  slug: 'thermae-yu-yokohama',
  name: 'Thermae-Yu',
  name_ja: 'テルマー湯',
  category: 'onsen-cafe',
  city: 'Yokohama',
  address: 'Minato Mirai, Nishi-ku',
  description: 'Complexe onsen avec café-restaurant, vue sur la baie',
  price_range: 3,
  photos: ['/images/cafes/00092b.jpg', '/images/cafes/00092m.jpg', '/images/cafes/00092g1.jpg', '/images/cafes/00092g2.jpg', '/images/cafes/00092g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/thermae',
  opening_days: [true, true, true, true, true, true, true],
  feature_ids: [1, 2, 5, 10],
  koi_number: 1567,
  super_koi_number: 456,
  review_ids: [78, 345, 891],
  latitude: 35.4551,
  longitude: 139.6364,
  created_at: new Date('2024-04-02')
},
{
  id: 93,
  slug: 'oedo-onsen-odaiba',
  name: 'Oedo Onsen Monogatari',
  name_ja: '大江戸温泉物語',
  category: 'onsen-cafe',
  city: 'Tokyo',
  address: 'Odaiba, Koto-ku',
  description: 'Village onsen avec multiples cafés et restaurants thématiques',
  price_range: 2,
  photos: ['/images/cafes/00093b.jpg', '/images/cafes/00093m.jpg', '/images/cafes/00093g1.jpg', '/images/cafes/00093g2.jpg', '/images/cafes/00093g3.jpg'],
  google_maps_url: 'https://maps.app.goo.gl/oedo',
  opening_days: [true, true, true, true, true, true, true],
  feature_ids: [1, 2, 4, 5, 10],
  koi_number: 2134,
  super_koi_number: 634,
  review_ids: [89, 234, 678, 912],
  latitude: 35.6249,
  longitude: 139.7798,
  created_at: new Date('2024-04-03')
}
]

export function getAllCafes(): Cafe[] {
  return cafes
}

export function getCafeBySlug(slug: string): Cafe | undefined {
  return cafes.find(cafe => cafe.slug === slug)
}

export function getCafesByCategory(categorySlug: string): Cafe[] {
  return cafes.filter(cafe => cafe.category === categorySlug)
}

export function getCafeById(id: number): Cafe | undefined {
  return cafes.find(cafe => cafe.id === id)
}