export interface Cafe {
  id: number
  slug: string
  name: string
  name_ja: string
  category: string
  city: string
  address: string
  description: string
  price_range: number
  photos: string[]
  google_maps_url: string
  opening_days: boolean[]
  feature_ids: number[]
  koi_number: number
  super_koi_number: number
  review_ids: number[]
  created_at: Date
}

export const cafes: Cafe[] = [
  // ===== OCHAYA (15 cafés) =====
  {
    id: 1,
    slug: 'ippodo-tea-kyoto',
    name: 'Ippodo Tea',
    name_ja: '一保堂茶舗',
    category: 'ochaya',
    city: 'Kyoto',
    address: 'Teramachi-dori Nijo, Nakagyo-ku',
    description: 'Maison de thé historique fondée en 1717, spécialiste du thé vert premium',
    price_range: 2,
    photos: ['/images/cafes/00001b.jpg', '/images/cafes/00001m.jpg', '/images/cafes/00001g1.jpg', '/images/cafes/00001g2.jpg', '/images/cafes/00001g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/ippodo',
    opening_days: [true, true, false, true, true, true, true],
    feature_ids: [1, 3, 5],
    koi_number: 342,
    super_koi_number: 87,
    review_ids: [21, 45],
    created_at: new Date('2024-01-01')
  },
  {
    id: 2,
    slug: 'tsujiri-gion',
    name: 'Tsujiri Gion',
    name_ja: '辻利 祇園',
    category: 'ochaya',
    city: 'Kyoto',
    address: 'Gion, Higashiyama-ku',
    description: 'Salon de thé emblématique de Gion, célèbre pour ses parfaits au matcha',
    price_range: 2,
    photos: ['/images/cafes/00002b.jpg', '/images/cafes/00002m.jpg', '/images/cafes/00002g1.jpg', '/images/cafes/00002g2.jpg', '/images/cafes/00002g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/tsujiri',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 2, 5, 8],
    koi_number: 521,
    super_koi_number: 143,
    review_ids: [32, 78, 156],
    created_at: new Date('2024-01-02')
  },
  {
    id: 3,
    slug: 'nakamura-tokichi-uji',
    name: 'Nakamura Tokichi',
    name_ja: '中村藤吉',
    category: 'ochaya',
    city: 'Uji',
    address: 'Uji-shi, Kyoto',
    description: 'Maison de thé centenaire dans la capitale du thé vert japonais',
    price_range: 3,
    photos: ['/images/cafes/00003b.jpg', '/images/cafes/00003m.jpg', '/images/cafes/00003g1.jpg', '/images/cafes/00003g2.jpg', '/images/cafes/00003g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/nakamura',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [3, 5, 6],
    koi_number: 689,
    super_koi_number: 201,
    review_ids: [12, 89, 234],
    created_at: new Date('2024-01-03')
  },
  {
    id: 4,
    slug: 'saryo-tsujiri-tokyo',
    name: 'Saryo Tsujiri',
    name_ja: '茶寮都路里',
    category: 'ochaya',
    city: 'Tokyo',
    address: 'Daikanyama, Shibuya-ku',
    description: 'Branche tokyoïte de la célèbre maison de thé de Kyoto',
    price_range: 2,
    photos: ['/images/cafes/00004b.jpg', '/images/cafes/00004m.jpg', '/images/cafes/00004g1.jpg', '/images/cafes/00004g2.jpg', '/images/cafes/00004g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/saryo',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [1, 5, 7],
    koi_number: 412,
    super_koi_number: 98,
    review_ids: [54, 123],
    created_at: new Date('2024-01-04')
  },
  {
    id: 5,
    slug: 'jugetsudo-ginza',
    name: 'Jugetsudo',
    name_ja: '寿月堂',
    category: 'ochaya',
    city: 'Tokyo',
    address: 'Ginza, Chuo-ku',
    description: 'Salon de thé raffiné dans le quartier chic de Ginza',
    price_range: 3,
    photos: ['/images/cafes/00005b.jpg', '/images/cafes/00005m.jpg', '/images/cafes/00005g1.jpg', '/images/cafes/00005g2.jpg', '/images/cafes/00005g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/jugetsudo',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [2, 3, 5],
    koi_number: 278,
    super_koi_number: 62,
    review_ids: [67, 189],
    created_at: new Date('2024-01-05')
  },
  {
    id: 6,
    slug: 'fukujuen-kyoto',
    name: 'Fukujuen',
    name_ja: '福寿園',
    category: 'ochaya',
    city: 'Kyoto',
    address: 'Karasuma, Nakagyo-ku',
    description: 'Maison de thé traditionnelle avec jardin zen',
    price_range: 2,
    photos: ['/images/cafes/00006b.jpg', '/images/cafes/00006m.jpg', '/images/cafes/00006g1.jpg', '/images/cafes/00006g2.jpg', '/images/cafes/00006g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/fukujuen',
    opening_days: [true, true, false, true, true, true, true],
    feature_ids: [1, 3, 5, 9],
    koi_number: 456,
    super_koi_number: 112,
    review_ids: [23, 98, 345],
    created_at: new Date('2024-01-06')
  },
  {
    id: 7,
    slug: 'higashiya-ginza',
    name: 'Higashiya',
    name_ja: '東屋',
    category: 'ochaya',
    city: 'Tokyo',
    address: 'Ginza, Chuo-ku',
    description: 'Salon de thé design alliant tradition et modernité',
    price_range: 3,
    photos: ['/images/cafes/00007b.jpg', '/images/cafes/00007m.jpg', '/images/cafes/00007g1.jpg', '/images/cafes/00007g2.jpg', '/images/cafes/00007g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/higashiya',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [2, 5, 6],
    koi_number: 623,
    super_koi_number: 178,
    review_ids: [45, 234, 567],
    created_at: new Date('2024-01-07')
  },
  {
    id: 8,
    slug: 'green-tea-restaurant-1899',
    name: 'Green Tea Restaurant 1899',
    name_ja: '茶房1899',
    category: 'ochaya',
    city: 'Tokyo',
    address: 'Ochanomizu, Bunkyo-ku',
    description: 'Restaurant-salon de thé avec cuisine fusion au matcha',
    price_range: 3,
    photos: ['/images/cafes/00008b.jpg', '/images/cafes/00008m.jpg', '/images/cafes/00008g1.jpg', '/images/cafes/00008g2.jpg', '/images/cafes/00008g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/1899',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [1, 4, 5],
    koi_number: 534,
    super_koi_number: 145,
    review_ids: [78, 156],
    created_at: new Date('2024-01-08')
  },
  {
    id: 9,
    slug: 'ocharaka-asakusa',
    name: 'Ocharaka',
    name_ja: 'お茶楽',
    category: 'ochaya',
    city: 'Tokyo',
    address: 'Asakusa, Taito-ku',
    description: 'Salon de thé traditionnel dans le quartier historique d\'Asakusa',
    price_range: 2,
    photos: ['/images/cafes/00009b.jpg', '/images/cafes/00009m.jpg', '/images/cafes/00009g1.jpg', '/images/cafes/00009g2.jpg', '/images/cafes/00009g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/ocharaka',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [3, 5],
    koi_number: 298,
    super_koi_number: 71,
    review_ids: [34, 123],
    created_at: new Date('2024-01-09')
  },
  {
    id: 10,
    slug: 'chasen-kamakura',
    name: 'Chasen',
    name_ja: '茶筅',
    category: 'ochaya',
    city: 'Kamakura',
    address: 'Komachi-dori, Kamakura-shi',
    description: 'Petit salon de thé authentique près des temples',
    price_range: 2,
    photos: ['/images/cafes/00010b.jpg', '/images/cafes/00010m.jpg', '/images/cafes/00010g1.jpg', '/images/cafes/00010g2.jpg', '/images/cafes/00010g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/chasen',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [1, 3, 5, 6],
    koi_number: 389,
    super_koi_number: 94,
    review_ids: [56, 189, 432],
    created_at: new Date('2024-01-10')
  },
  {
    id: 11,
    slug: 'sakurai-nara',
    name: 'Sakurai Japanese Tea Experience',
    name_ja: '櫻井焙茶研究所',
    category: 'ochaya',
    city: 'Nara',
    address: 'Naramachi, Nara-shi',
    description: 'Expérience immersive du thé torréfié hojicha',
    price_range: 3,
    photos: ['/images/cafes/00011b.jpg', '/images/cafes/00011m.jpg', '/images/cafes/00011g1.jpg', '/images/cafes/00011g2.jpg', '/images/cafes/00011g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/sakurai',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [2, 5, 7],
    koi_number: 712,
    super_koi_number: 203,
    review_ids: [23, 145, 678],
    created_at: new Date('2024-01-11')
  },
  {
    id: 12,
    slug: 'chacha-no-ma-shibuya',
    name: 'Chacha no Ma',
    name_ja: '茶々の間',
    category: 'ochaya',
    city: 'Tokyo',
    address: 'Shibuya, Shibuya-ku',
    description: 'Salon de thé moderne avec vue panoramique sur Shibuya',
    price_range: 2,
    photos: ['/images/cafes/00012b.jpg', '/images/cafes/00012m.jpg', '/images/cafes/00012g1.jpg', '/images/cafes/00012g2.jpg', '/images/cafes/00012g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/chachanoma',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 4, 5, 8],
    koi_number: 445,
    super_koi_number: 119,
    review_ids: [67, 234],
    created_at: new Date('2024-01-12')
  },
  {
    id: 13,
    slug: 'cha-ginza',
    name: 'CHA GINZA',
    name_ja: '茶 銀座',
    category: 'ochaya',
    city: 'Tokyo',
    address: 'Ginza, Chuo-ku',
    description: 'Boutique-salon de thé luxueux au cœur de Ginza',
    price_range: 3,
    photos: ['/images/cafes/00013b.jpg', '/images/cafes/00013m.jpg', '/images/cafes/00013g1.jpg', '/images/cafes/00013g2.jpg', '/images/cafes/00013g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/chaginza',
    opening_days: [true, true, false, true, true, true, true],
    feature_ids: [2, 3, 5],
    koi_number: 567,
    super_koi_number: 156,
    review_ids: [89, 345],
    created_at: new Date('2024-01-13')
  },
  {
    id: 14,
    slug: 'ryokucha-takezawa',
    name: 'Ryokucha Takezawa',
    name_ja: '緑茶竹澤',
    category: 'ochaya',
    city: 'Shizuoka',
    address: 'Shizuoka-shi',
    description: 'Salon de thé dans la région productrice de Shizuoka',
    price_range: 2,
    photos: ['/images/cafes/00014b.jpg', '/images/cafes/00014m.jpg', '/images/cafes/00014g1.jpg', '/images/cafes/00014g2.jpg', '/images/cafes/00014g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/ryokucha',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [1, 3, 5, 9],
    koi_number: 321,
    super_koi_number: 78,
    review_ids: [45, 178],
    created_at: new Date('2024-01-14')
  },
  {
    id: 15,
    slug: 'matcha-stand-maruni',
    name: 'Matcha Stand Maruni',
    name_ja: 'まるに抹茶スタンド',
    category: 'ochaya',
    city: 'Kyoto',
    address: 'Arashiyama, Ukyo-ku',
    description: 'Stand de matcha à emporter avec vue sur la bambouseraie',
    price_range: 1,
    photos: ['/images/cafes/00015b.jpg', '/images/cafes/00015m.jpg', '/images/cafes/00015g1.jpg', '/images/cafes/00015g2.jpg', '/images/cafes/00015g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/maruni',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [5, 7],
    koi_number: 234,
    super_koi_number: 52,
    review_ids: [12, 89],
    created_at: new Date('2024-01-15')
  },

  // ===== KISSATEN (15 cafés) =====
  {
    id: 16,
    slug: 'chatei-hatou',
    name: 'Chatei Hatou',
    name_ja: '茶亭羽當',
    category: 'kissaten',
    city: 'Tokyo',
    address: 'Jingumae, Shibuya-ku',
    description: 'Kissaten emblématique de Shibuya depuis 1989, café siphon légendaire',
    price_range: 2,
    photos: ['/images/cafes/00016b.jpg', '/images/cafes/00016m.jpg', '/images/cafes/00016g1.jpg', '/images/cafes/00016g2.jpg', '/images/cafes/00016g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/chateihatou',
    opening_days: [true, true, false, true, true, true, false],
    feature_ids: [1, 3, 6],
    koi_number: 892,
    super_koi_number: 245,
    review_ids: [23, 156, 543],
    created_at: new Date('2024-01-16')
  },
  {
    id: 17,
    slug: 'cafe-de-lambre',
    name: 'Cafe de l\'Ambre',
    name_ja: 'カフェ・ド・ランブル',
    category: 'kissaten',
    city: 'Tokyo',
    address: 'Ginza, Chuo-ku',
    description: 'Institution historique de Ginza fondée en 1948, temple du café vieilli',
    price_range: 3,
    photos: ['/images/cafes/00017b.jpg', '/images/cafes/00017m.jpg', '/images/cafes/00017g1.jpg', '/images/cafes/00017g2.jpg', '/images/cafes/00017g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/lambre',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [3, 5, 6],
    koi_number: 1234,
    super_koi_number: 412,
    review_ids: [34, 234, 789],
    created_at: new Date('2024-01-17')
  },
  {
    id: 18,
    slug: 'cafe-bach',
    name: 'Cafe Bach',
    name_ja: 'カフェ・バッハ',
    category: 'kissaten',
    city: 'Tokyo',
    address: 'Taito-ku',
    description: 'Kissaten de renommée mondiale, maître torréfacteur depuis 1968',
    price_range: 2,
    photos: ['/images/cafes/00018b.jpg', '/images/cafes/00018m.jpg', '/images/cafes/00018g1.jpg', '/images/cafes/00018g2.jpg', '/images/cafes/00018g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/bach',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [1, 3, 5],
    koi_number: 1045,
    super_koi_number: 328,
    review_ids: [45, 267, 891],
    created_at: new Date('2024-01-18')
  },
  {
    id: 19,
    slug: 'lion-shibuya',
    name: 'Lion',
    name_ja: 'ライオン',
    category: 'kissaten',
    city: 'Tokyo',
    address: 'Dogenzaka, Shibuya-ku',
    description: 'Kissaten musical avec concerts de musique classique quotidiens',
    price_range: 2,
    photos: ['/images/cafes/00019b.jpg', '/images/cafes/00019m.jpg', '/images/cafes/00019g1.jpg', '/images/cafes/00019g2.jpg', '/images/cafes/00019g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/lion',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [3, 6, 8],
    koi_number: 678,
    super_koi_number: 189,
    review_ids: [78, 345],
    created_at: new Date('2024-01-19')
  },
  {
    id: 20,
    slug: 'almond-ginza',
    name: 'Almond',
    name_ja: 'アーモンド',
    category: 'kissaten',
    city: 'Tokyo',
    address: 'Ginza, Chuo-ku',
    description: 'Kissaten iconique de Ginza, point de rendez-vous légendaire',
    price_range: 2,
    photos: ['/images/cafes/00020b.jpg', '/images/cafes/00020m.jpg', '/images/cafes/00020g1.jpg', '/images/cafes/00020g2.jpg', '/images/cafes/00020g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/almond',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 3, 5, 7],
    koi_number: 534,
    super_koi_number: 142,
    review_ids: [56, 234],
    created_at: new Date('2024-01-20')
  },
  {
    id: 21,
    slug: 'coffee-hall-kugutsusou',
    name: 'Coffee Hall Kugutsusou',
    name_ja: '珈琲舘くぐつ草',
    category: 'kissaten',
    city: 'Tokyo',
    address: 'Yotsuya, Shinjuku-ku',
    description: 'Kissaten vintage avec collection de tasses anciennes',
    price_range: 2,
    photos: ['/images/cafes/00021b.jpg', '/images/cafes/00021m.jpg', '/images/cafes/00021g1.jpg', '/images/cafes/00021g2.jpg', '/images/cafes/00021g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/kugutsusou',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [3, 6],
    koi_number: 423,
    super_koi_number: 98,
    review_ids: [23, 167],
    created_at: new Date('2024-01-21')
  },
  {
    id: 22,
    slug: 'tsukiji-tamura',
    name: 'Tsukiji Tamura',
    name_ja: '築地田村',
    category: 'kissaten',
    city: 'Tokyo',
    address: 'Tsukiji, Chuo-ku',
    description: 'Kissaten historique du marché de Tsukiji depuis 1924',
    price_range: 2,
    photos: ['/images/cafes/00022b.jpg', '/images/cafes/00022m.jpg', '/images/cafes/00022g1.jpg', '/images/cafes/00022g2.jpg', '/images/cafes/00022g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/tamura',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [1, 3, 5],
    koi_number: 789,
    super_koi_number: 234,
    review_ids: [45, 289, 654],
    created_at: new Date('2024-01-22')
  },
  {
    id: 23,
    slug: 'café-paulista',
    name: 'Café Paulista',
    name_ja: 'カフェーパウリスタ',
    category: 'kissaten',
    city: 'Tokyo',
    address: 'Ginza, Chuo-ku',
    description: 'Premier café japonais fondé en 1911, importateur historique de café brésilien',
    price_range: 2,
    photos: ['/images/cafes/00023b.jpg', '/images/cafes/00023m.jpg', '/images/cafes/00023g1.jpg', '/images/cafes/00023g2.jpg', '/images/cafes/00023g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/paulista',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [3, 5, 6],
    koi_number: 956,
    super_koi_number: 287,
    review_ids: [67, 345, 876],
    created_at: new Date('2024-01-23')
  },
  {
    id: 24,
    slug: 'rosetta',
    name: 'Rosetta',
    name_ja: 'ロゼッタ',
    category: 'kissaten',
    city: 'Osaka',
    address: 'Umeda, Kita-ku',
    description: 'Kissaten d\'Osaka célèbre pour son pudding nostalgique',
    price_range: 2,
    photos: ['/images/cafes/00024b.jpg', '/images/cafes/00024m.jpg', '/images/cafes/00024g1.jpg', '/images/cafes/00024g2.jpg', '/images/cafes/00024g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/rosetta',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [1, 3, 5, 7],
    koi_number: 612,
    super_koi_number: 178,
    review_ids: [34, 189],
    created_at: new Date('2024-01-24')
  },
  {
    id: 25,
    slug: 'francois-kyoto',
    name: 'Francois',
    name_ja: 'フランソア',
    category: 'kissaten',
    city: 'Kyoto',
    address: 'Kawaramachi, Nakagyo-ku',
    description: 'Kissaten de Kyoto au décor Art Déco, ouvert depuis 1934',
    price_range: 2,
    photos: ['/images/cafes/00025b.jpg', '/images/cafes/00025m.jpg', '/images/cafes/00025g1.jpg', '/images/cafes/00025g2.jpg', '/images/cafes/00025g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/francois',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [3, 6, 8],
    koi_number: 845,
    super_koi_number: 221,
    review_ids: [56, 267, 789],
    created_at: new Date('2024-01-25')
  },
  {
    id: 26,
    slug: 'smart-coffee-kyoto',
    name: 'Smart Coffee',
    name_ja: 'スマート珈琲店',
    category: 'kissaten',
    city: 'Kyoto',
    address: 'Teramachi, Nakagyo-ku',
    description: 'Kissaten historique de Kyoto, café torréfié sur place depuis 1932',
    price_range: 2,
    photos: ['/images/cafes/00026b.jpg', '/images/cafes/00026m.jpg', '/images/cafes/00026g1.jpg', '/images/cafes/00026g2.jpg', '/images/cafes/00026g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/smartcoffee',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [1, 3, 5],
    koi_number: 734,
    super_koi_number: 203,
    review_ids: [78, 345],
    created_at: new Date('2024-01-26')
  },
  {
    id: 27,
    slug: 'rusk-kobe',
    name: 'Rusk',
    name_ja: 'ラスク',
    category: 'kissaten',
    city: 'Kobe',
    address: 'Kitano, Chuo-ku',
    description: 'Kissaten rétro de Kobe dans le quartier européen',
    price_range: 2,
    photos: ['/images/cafes/00027b.jpg', '/images/cafes/00027m.jpg', '/images/cafes/00027g1.jpg', '/images/cafes/00027g2.jpg', '/images/cafes/00027g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/rusk',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [3, 5, 6],
    koi_number: 456,
    super_koi_number: 123,
    review_ids: [45, 198],
    created_at: new Date('2024-01-27')
  },
  {
    id: 28,
    slug: 'meikyoku-kissa-lion',
    name: 'Meikyoku Kissa Lion',
    name_ja: '名曲喫茶ライオン',
    category: 'kissaten',
    city: 'Tokyo',
    address: 'Shibuya, Shibuya-ku',
    description: 'Kissaten musical légendaire avec système audio haute-fidélité',
    price_range: 2,
    photos: ['/images/cafes/00028b.jpg', '/images/cafes/00028m.jpg', '/images/cafes/00028g1.jpg', '/images/cafes/00028g2.jpg', '/images/cafes/00028g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/meikyoku',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [3, 6, 8],
    koi_number: 923,
    super_koi_number: 267,
    review_ids: [89, 345, 678],
    created_at: new Date('2024-01-28')
  },
  {
    id: 29,
    slug: 'mikado-coffee',
    name: 'Mikado Coffee',
    name_ja: 'ミカド珈琲',
    category: 'kissaten',
    city: 'Tokyo',
    address: 'Kyobashi, Chuo-ku',
    description: 'Kissaten depuis 1948, torréfaction artisanale quotidienne',
    price_range: 2,
    photos: ['/images/cafes/00029b.jpg', '/images/cafes/00029m.jpg', '/images/cafes/00029g1.jpg', '/images/cafes/00029g2.jpg', '/images/cafes/00029g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/mikado',
    opening_days: [true, true, false, true, true, true, true],
    feature_ids: [1, 3, 5],
    koi_number: 567,
    super_koi_number: 145,
    review_ids: [23, 234],
    created_at: new Date('2024-01-29')
  },
  {
    id: 30,
    slug: 'den-ginza',
    name: 'Den',
    name_ja: '電',
    category: 'kissaten',
    city: 'Tokyo',
    address: 'Ginza, Chuo-ku',
    description: 'Kissaten minimaliste avec ambiance intime et feutrée',
    price_range: 2,
    photos: ['/images/cafes/00030b.jpg', '/images/cafes/00030m.jpg', '/images/cafes/00030g1.jpg', '/images/cafes/00030g2.jpg', '/images/cafes/00030g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/den',
    opening_days: [false, true, true, true, true, true, false],
    feature_ids: [3, 5],
    koi_number: 389,
    super_koi_number: 87,
    review_ids: [56, 178],
    created_at: new Date('2024-01-30')
  },

  // ===== JUNSEIKISSATEN (15 cafés) =====
  {
    id: 31,
    slug: 'takachiho-jingumae',
    name: 'Takachiho',
    name_ja: '高千穂',
    category: 'junseikissaten',
    city: 'Tokyo',
    address: 'Jingumae, Shibuya-ku',
    description: 'Pure kissaten silencieux, café siphon et méditation',
    price_range: 2,
    photos: ['/images/cafes/00031b.jpg', '/images/cafes/00031m.jpg', '/images/cafes/00031g1.jpg', '/images/cafes/00031g2.jpg', '/images/cafes/00031g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/takachiho',
    opening_days: [true, true, false, true, true, true, false],
    feature_ids: [3, 5],
    koi_number: 678,
    super_koi_number: 189,
    review_ids: [34, 234, 567],
    created_at: new Date('2024-01-31')
  },
  {
    id: 32,
    slug: 'sabouru-jimbocho',
    name: 'Sabouru',
    name_ja: 'さぼうる',
    category: 'junseikissaten',
    city: 'Tokyo',
    address: 'Jimbocho, Chiyoda-ku',
    description: 'Institution de Jimbocho depuis 1955, ambiance studieuse garantie',
    price_range: 1,
    photos: ['/images/cafes/00032b.jpg', '/images/cafes/00032m.jpg', '/images/cafes/00032g1.jpg', '/images/cafes/00032g2.jpg', '/images/cafes/00032g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/sabouru',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [1, 3, 6],
    koi_number: 1123,
    super_koi_number: 345,
    review_ids: [45, 289, 765],
    created_at: new Date('2024-02-01')
  },
  {
    id: 33,
    slug: 'tsubakiya-kanda',
    name: 'Tsubakiya',
    name_ja: '椿屋珈琲店',
    category: 'junseikissaten',
    city: 'Tokyo',
    address: 'Kanda, Chiyoda-ku',
    description: 'Pure kissaten avec décor Taisho romantique',
    price_range: 2,
    photos: ['/images/cafes/00033b.jpg', '/images/cafes/00033m.jpg', '/images/cafes/00033g1.jpg', '/images/cafes/00033g2.jpg', '/images/cafes/00033g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/tsubakiya',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [3, 5, 6],
    koi_number: 834,
    super_koi_number: 221,
    review_ids: [67, 345],
    created_at: new Date('2024-02-02')
  },
  {
    id: 34,
    slug: 'ladrio-ebisu',
    name: 'Ladrio',
    name_ja: 'ラドリオ',
    category: 'junseikissaten',
    city: 'Tokyo',
    address: 'Ebisu, Shibuya-ku',
    description: 'Kissaten pur avec règle du silence absolu',
    price_range: 2,
    photos: ['/images/cafes/00034b.jpg', '/images/cafes/00034m.jpg', '/images/cafes/00034g1.jpg', '/images/cafes/00034g2.jpg', '/images/cafes/00034g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/ladrio',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [3, 5],
    koi_number: 456,
    super_koi_number: 112,
    review_ids: [23, 156],
    created_at: new Date('2024-02-03')
  },
  {
    id: 35,
    slug: 'hakoniwa-nakano',
    name: 'Hakoniwa',
    name_ja: '箱庭',
    category: 'junseikissaten',
    city: 'Tokyo',
    address: 'Nakano, Nakano-ku',
    description: 'Pure kissaten caché avec jardin miniature zen',
    price_range: 2,
    photos: ['/images/cafes/00035b.jpg', '/images/cafes/00035m.jpg', '/images/cafes/00035g1.jpg', '/images/cafes/00035g2.jpg', '/images/cafes/00035g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/hakoniwa',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [3, 5, 9],
    koi_number: 523,
    super_koi_number: 134,
    review_ids: [45, 234, 543],
    created_at: new Date('2024-02-04')
  },
  {
    id: 36,
    slug: 'fuji-shibuya',
    name: 'Fuji',
    name_ja: '富士',
    category: 'junseikissaten',
    city: 'Tokyo',
    address: 'Shibuya, Shibuya-ku',
    description: 'Junseikissaten puriste, interdiction formelle de conversations',
    price_range: 2,
    photos: ['/images/cafes/00036b.jpg', '/images/cafes/00036m.jpg', '/images/cafes/00036g1.jpg', '/images/cafes/00036g2.jpg', '/images/cafes/00036g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/fuji',
    opening_days: [false, true, true, true, true, true, false],
    feature_ids: [3, 5],
    koi_number: 712,
    super_koi_number: 198,
    review_ids: [78, 345],
    created_at: new Date('2024-02-05')
  },
  {
    id: 37,
    slug: 'bundan-kanda',
    name: 'Bundan',
    name_ja: '文壇',
    category: 'junseikissaten',
    city: 'Tokyo',
    address: 'Kanda, Chiyoda-ku',
    description: 'Kissaten littéraire où écrivains venaient travailler en silence',
    price_range: 2,
    photos: ['/images/cafes/00037b.jpg', '/images/cafes/00037m.jpg', '/images/cafes/00037g1.jpg', '/images/cafes/00037g2.jpg', '/images/cafes/00037g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/bundan',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [1, 3, 6],
    koi_number: 645,
    super_koi_number: 176,
    review_ids: [56, 267],
    created_at: new Date('2024-02-06')
  },
  {
    id: 38,
    slug: 'shizuka-ikebukuro',
    name: 'Shizuka',
    name_ja: '静',
    category: 'junseikissaten',
    city: 'Tokyo',
    address: 'Ikebukuro, Toshima-ku',
    description: 'Pure kissaten minimaliste dédié au silence et à la contemplation',
    price_range: 2,
    photos: ['/images/cafes/00038b.jpg', '/images/cafes/00038m.jpg', '/images/cafes/00038g1.jpg', '/images/cafes/00038g2.jpg', '/images/cafes/00038g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/shizuka',
    opening_days: [true, true, false, true, true, true, true],
    feature_ids: [3, 5],
    koi_number: 389,
    super_koi_number: 94,
    review_ids: [34, 178],
    created_at: new Date('2024-02-07')
  },
  {
    id: 39,
    slug: 'contemplation-kyoto',
    name: 'Contemplation',
    name_ja: '瞑想',
    category: 'junseikissaten',
    city: 'Kyoto',
    address: 'Kiyamachi, Nakagyo-ku',
    description: 'Junseikissaten de Kyoto avec vue sur la rivière Kamo',
    price_range: 2,
    photos: ['/images/cafes/00039b.jpg', '/images/cafes/00039m.jpg', '/images/cafes/00039g1.jpg', '/images/cafes/00039g2.jpg', '/images/cafes/00039g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/contemplation',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [3, 5, 9],
    koi_number: 567,
    super_koi_number: 145,
    review_ids: [67, 289],
    created_at: new Date('2024-02-08')
  },
  {
    id: 40,
    slug: 'seijaku-osaka',
    name: 'Seijaku',
    name_ja: '静寂',
    category: 'junseikissaten',
    city: 'Osaka',
    address: 'Namba, Chuo-ku',
    description: 'Pure kissaten d\'Osaka, ambiance monastique garantie',
    price_range: 2,
    photos: ['/images/cafes/00040b.jpg', '/images/cafes/00040m.jpg', '/images/cafes/00040g1.jpg', '/images/cafes/00040g2.jpg', '/images/cafes/00040g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/seijaku',
    opening_days: [true, true, true, false, true, true, false],
    feature_ids: [3, 5],
    koi_number: 423,
    super_koi_number: 98,
    review_ids: [45, 198],
    created_at: new Date('2024-02-09')
  },
  {
    id: 41,
    slug: 'mokuteki-nagoya',
    name: 'Mokuteki',
    name_ja: '黙的',
    category: 'junseikissaten',
    city: 'Nagoya',
    address: 'Sakae, Naka-ku',
    description: 'Junseikissaten de Nagoya, café et silence uniquement',
    price_range: 2,
    photos: ['/images/cafes/00041b.jpg', '/images/cafes/00041m.jpg', '/images/cafes/00041g1.jpg', '/images/cafes/00041g2.jpg', '/images/cafes/00041g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/mokuteki',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [3, 5],
    koi_number: 512,
    super_koi_number: 123,
    review_ids: [23, 156],
    created_at: new Date('2024-02-10')
  },
  {
    id: 42,
    slug: 'chinmoku-hiroshima',
    name: 'Chinmoku',
    name_ja: '沈黙',
    category: 'junseikissaten',
    city: 'Hiroshima',
    address: 'Hondori, Naka-ku',
    description: 'Pure kissaten d\'Hiroshima dans une ruelle tranquille',
    price_range: 2,
    photos: ['/images/cafes/00042b.jpg', '/images/cafes/00042m.jpg', '/images/cafes/00042g1.jpg', '/images/cafes/00042g2.jpg', '/images/cafes/00042g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/chinmoku',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [3, 5],
    koi_number: 345,
    super_koi_number: 78,
    review_ids: [34, 167],
    created_at: new Date('2024-02-11')
  },
  {
    id: 43,
    slug: 'maboroshi-fukuoka',
    name: 'Maboroshi',
    name_ja: '幻',
    category: 'junseikissaten',
    city: 'Fukuoka',
    address: 'Daimyo, Chuo-ku',
    description: 'Junseikissaten caché de Fukuoka, sur rendez-vous uniquement',
    price_range: 3,
    photos: ['/images/cafes/00043b.jpg', '/images/cafes/00043m.jpg', '/images/cafes/00043g1.jpg', '/images/cafes/00043g2.jpg', '/images/cafes/00043g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/maboroshi',
    opening_days: [true, true, false, true, true, false, false],
    feature_ids: [3, 5],
    koi_number: 234,
    super_koi_number: 56,
    review_ids: [12, 89],
    created_at: new Date('2024-02-12')
  },
  {
    id: 44,
    slug: 'zannen-yokohama',
    name: 'Zannen',
    name_ja: '残念',
    category: 'junseikissaten',
    city: 'Yokohama',
    address: 'Motomachi, Naka-ku',
    description: 'Pure kissaten de Yokohama avec vue sur le port',
    price_range: 2,
    photos: ['/images/cafes/00044b.jpg', '/images/cafes/00044m.jpg', '/images/cafes/00044g1.jpg', '/images/cafes/00044g2.jpg', '/images/cafes/00044g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/zannen',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [3, 5, 9],
    koi_number: 478,
    super_koi_number: 112,
    review_ids: [45, 234],
    created_at: new Date('2024-02-13')
  },
  {
    id: 45,
    slug: 'muon-sapporo',
    name: 'Muon',
    name_ja: '無音',
    category: 'junseikissaten',
    city: 'Sapporo',
    address: 'Susukino, Chuo-ku',
    description: 'Junseikissaten de Sapporo, refuge silencieux du nord',
    price_range: 2,
    photos: ['/images/cafes/00045b.jpg', '/images/cafes/00045m.jpg', '/images/cafes/00045g1.jpg', '/images/cafes/00045g2.jpg', '/images/cafes/00045g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/muon',
    opening_days: [false, true, true, true, true, true, false],
    feature_ids: [3, 5],
    koi_number: 289,
    super_koi_number: 67,
    review_ids: [23, 145],
    created_at: new Date('2024-02-14')
  },

  // ===== BOOK CAFE (15 cafés) =====
  {
    id: 46,
    slug: 'tsutaya-daikanyama',
    name: 'Tsutaya Books Daikanyama',
    name_ja: '蔦屋書店 代官山',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Daikanyama, Shibuya-ku',
    description: 'Librairie-café emblématique, temple du design et de la culture',
    price_range: 3,
    photos: ['/images/cafes/00046b.jpg', '/images/cafes/00046m.jpg', '/images/cafes/00046g1.jpg', '/images/cafes/00046g2.jpg', '/images/cafes/00046g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/tsutaya',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 2, 4, 5, 7],
    koi_number: 1456,
    super_koi_number: 423,
    review_ids: [34, 267, 891],
    created_at: new Date('2024-02-15')
  },
  {
    id: 47,
    slug: 'book-and-bed-tokyo',
    name: 'Book and Bed Tokyo',
    name_ja: 'ブックアンドベッド東京',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Ikebukuro, Toshima-ku',
    description: 'Concept unique de librairie-café avec lits capsules pour lecteurs',
    price_range: 2,
    photos: ['/images/cafes/00047b.jpg', '/images/cafes/00047m.jpg', '/images/cafes/00047g1.jpg', '/images/cafes/00047g2.jpg', '/images/cafes/00047g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/bookandbed',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 4, 5, 7],
    koi_number: 1234,
    super_koi_number: 378,
    review_ids: [45, 289, 654],
    created_at: new Date('2024-02-16')
  },
  {
    id: 48,
    slug: 'shibuya-publishing-booksellers',
    name: 'Shibuya Publishing & Booksellers',
    name_ja: '渋谷パブリッシング＆ブックセラーズ',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Kamiyamacho, Shibuya-ku',
    description: 'Librairie-café indépendante spécialisée en culture et art',
    price_range: 2,
    photos: ['/images/cafes/00048b.jpg', '/images/cafes/00048m.jpg', '/images/cafes/00048g1.jpg', '/images/cafes/00048g2.jpg', '/images/cafes/00048g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/spbs',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [1, 4, 5],
    koi_number: 789,
    super_koi_number: 234,
    review_ids: [67, 345],
    created_at: new Date('2024-02-17')
  },
  {
    id: 49,
    slug: 'readan-deat-omotesando',
    name: 'Readan Deat',
    name_ja: 'リーダンディート',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Omotesando, Shibuya-ku',
    description: 'Book café avec galerie d\'art contemporain intégrée',
    price_range: 3,
    photos: ['/images/cafes/00049b.jpg', '/images/cafes/00049m.jpg', '/images/cafes/00049g1.jpg', '/images/cafes/00049g2.jpg', '/images/cafes/00049g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/readan',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [2, 4, 5, 8],
    koi_number: 923,
    super_koi_number: 287,
    review_ids: [78, 234, 567],
    created_at: new Date('2024-02-18')
  },
  {
    id: 50,
    slug: 'utrecht-shibuya',
    name: 'Utrecht',
    name_ja: 'ユトレヒト',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Shibuya, Shibuya-ku',
    description: 'Librairie-café spécialisée en design graphique et magazines',
    price_range: 2,
    photos: ['/images/cafes/00050b.jpg', '/images/cafes/00050m.jpg', '/images/cafes/00050g1.jpg', '/images/cafes/00050g2.jpg', '/images/cafes/00050g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/utrecht',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 4, 5, 7],
    koi_number: 656,
    super_koi_number: 189,
    review_ids: [56, 289],
    created_at: new Date('2024-02-19')
  },
  {
    id: 51,
    slug: 'cow-books-nakameguro',
    name: 'COW BOOKS',
    name_ja: 'カウブックス',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Nakameguro, Meguro-ku',
    description: 'Librairie vintage avec café, sélection de livres d\'occasion soignée',
    price_range: 2,
    photos: ['/images/cafes/00051b.jpg', '/images/cafes/00051m.jpg', '/images/cafes/00051g1.jpg', '/images/cafes/00051g2.jpg', '/images/cafes/00051g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/cowbooks',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [1, 4, 5, 6],
    koi_number: 534,
    super_koi_number: 145,
    review_ids: [34, 178],
    created_at: new Date('2024-02-20')
  },
  {
    id: 52,
    slug: 'bunkyodo-umeda',
    name: 'Bunkyodo',
    name_ja: '文教堂',
    category: 'book-cafe',
    city: 'Osaka',
    address: 'Umeda, Kita-ku',
    description: 'Grande librairie-café d\'Osaka sur plusieurs étages',
    price_range: 2,
    photos: ['/images/cafes/00052b.jpg', '/images/cafes/00052m.jpg', '/images/cafes/00052g1.jpg', '/images/cafes/00052g2.jpg', '/images/cafes/00052g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/bunkyodo',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 2, 4, 5],
    koi_number: 712,
    super_koi_number: 201,
    review_ids: [45, 234, 678],
    created_at: new Date('2024-02-21')
  },
  {
    id: 53,
    slug: 'keibunsha-ichijoji',
    name: 'Keibunsha',
    name_ja: '恵文社一乗寺店',
    category: 'book-cafe',
    city: 'Kyoto',
    address: 'Ichijoji, Sakyo-ku',
    description: 'Librairie-café indépendante culte de Kyoto',
    price_range: 2,
    photos: ['/images/cafes/00053b.jpg', '/images/cafes/00053m.jpg', '/images/cafes/00053g1.jpg', '/images/cafes/00053g2.jpg', '/images/cafes/00053g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/keibunsha',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [1, 4, 5, 9],
    koi_number: 845,
    super_koi_number: 256,
    review_ids: [67, 345, 789],
    created_at: new Date('2024-02-22')
  },
  {
    id: 54,
    slug: 'hoshinobooks-jimbocho',
    name: 'Hoshino Books',
    name_ja: '星野書店',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Jimbocho, Chiyoda-ku',
    description: 'Librairie-café dans le quartier des livres de Tokyo',
    price_range: 2,
    photos: ['/images/cafes/00054b.jpg', '/images/cafes/00054m.jpg', '/images/cafes/00054g1.jpg', '/images/cafes/00054g2.jpg', '/images/cafes/00054g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/hoshino',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [1, 4, 5],
    koi_number: 623,
    super_koi_number: 178,
    review_ids: [45, 267],
    created_at: new Date('2024-02-23')
  },
  {
    id: 55,
    slug: 'books-bunny-koenji',
    name: 'Books Bunny',
    name_ja: 'ブックスバニー',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Koenji, Suginami-ku',
    description: 'Petite librairie-café cosy spécialisée en littérature',
    price_range: 2,
    photos: ['/images/cafes/00055b.jpg', '/images/cafes/00055m.jpg', '/images/cafes/00055g1.jpg', '/images/cafes/00055g2.jpg', '/images/cafes/00055g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/booksbunny',
    opening_days: [true, true, false, true, true, true, true],
    feature_ids: [1, 4, 5],
    koi_number: 412,
    super_koi_number: 98,
    review_ids: [23, 156],
    created_at: new Date('2024-02-24')
  },
  {
    id: 56,
    slug: 'papier-labo-harajuku',
    name: 'Papier Labo',
    name_ja: 'パピエラボ',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Harajuku, Shibuya-ku',
    description: 'Book café avec galerie d\'expositions photographiques',
    price_range: 2,
    photos: ['/images/cafes/00056b.jpg', '/images/cafes/00056m.jpg', '/images/cafes/00056g1.jpg', '/images/cafes/00056g2.jpg', '/images/cafes/00056g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/papier',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [2, 4, 5, 8],
    koi_number: 567,
    super_koi_number: 145,
    review_ids: [56, 234, 543],
    created_at: new Date('2024-02-25')
  },
  {
    id: 57,
    slug: 'komiyama-tokyo',
    name: 'Komiyama Tokyo',
    name_ja: '小宮山書店',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Jimbocho, Chiyoda-ku',
    description: 'Librairie ancienne avec café, livres rares et d\'occasion',
    price_range: 2,
    photos: ['/images/cafes/00057b.jpg', '/images/cafes/00057m.jpg', '/images/cafes/00057g1.jpg', '/images/cafes/00057g2.jpg', '/images/cafes/00057g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/komiyama',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [1, 4, 5, 6],
    koi_number: 489,
    super_koi_number: 123,
    review_ids: [34, 189],
    created_at: new Date('2024-02-26')
  },
  {
    id: 58,
    slug: 'morioka-shoten-ginza',
    name: 'Morioka Shoten',
    name_ja: '森岡書店',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Ginza, Chuo-ku',
    description: 'Librairie-galerie unique présentant un seul livre à la fois',
    price_range: 2,
    photos: ['/images/cafes/00058b.jpg', '/images/cafes/00058m.jpg', '/images/cafes/00058g1.jpg', '/images/cafes/00058g2.jpg', '/images/cafes/00058g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/morioka',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [2, 4, 5, 8],
    koi_number: 756,
    super_koi_number: 212,
    review_ids: [67, 345, 678],
    created_at: new Date('2024-02-27')
  },
  {
    id: 59,
    slug: 'libro-ikebukuro',
    name: 'Libro',
    name_ja: 'リブロ',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Ikebukuro, Toshima-ku',
    description: 'Grande chaîne de librairies-cafés, sélection éclectique',
    price_range: 2,
    photos: ['/images/cafes/00059b.jpg', '/images/cafes/00059m.jpg', '/images/cafes/00059g1.jpg', '/images/cafes/00059g2.jpg', '/images/cafes/00059g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/libro',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 2, 4, 5],
    koi_number: 534,
    super_koi_number: 134,
    review_ids: [45, 234],
    created_at: new Date('2024-02-28')
  },
  {
    id: 60,
    slug: 'gallery-so-akasaka',
    name: 'Gallery SO',
    name_ja: 'ギャラリー艸',
    category: 'book-cafe',
    city: 'Tokyo',
    address: 'Akasaka, Minato-ku',
    description: 'Galerie-café avec librairie d\'art et design',
    price_range: 3,
    photos: ['/images/cafes/00060b.jpg', '/images/cafes/00060m.jpg', '/images/cafes/00060g1.jpg', '/images/cafes/00060g2.jpg', '/images/cafes/00060g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/galleryso',
    opening_days: [false, true, true, true, true, true, false],
    feature_ids: [2, 4, 5, 8],
    koi_number: 423,
    super_koi_number: 98,
    review_ids: [23, 167, 432],
    created_at: new Date('2024-03-01')
  },

  // ===== THIRD WAVE (15 cafés) =====
  {
    id: 61,
    slug: 'onibus-coffee-nakameguro',
    name: 'Onibus Coffee',
    name_ja: 'オニバスコーヒー',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Nakameguro, Meguro-ku',
    description: 'Torréfacteur third wave pionnier de Tokyo, café de spécialité',
    price_range: 2,
    photos: ['/images/cafes/00061b.jpg', '/images/cafes/00061m.jpg', '/images/cafes/00061g1.jpg', '/images/cafes/00061g2.jpg', '/images/cafes/00061g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/onibus',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 4, 5, 7],
    koi_number: 1234,
    super_koi_number: 389,
    review_ids: [45, 234, 765],
    created_at: new Date('2024-03-02')
  },
  {
    id: 62,
    slug: 'about-life-coffee-brewers',
    name: 'About Life Coffee Brewers',
    name_ja: 'アバウトライフコーヒーブリュワーズ',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Shibuya, Shibuya-ku',
    description: 'Café third wave minimaliste, focus absolu sur la qualité',
    price_range: 2,
    photos: ['/images/cafes/00062b.jpg', '/images/cafes/00062m.jpg', '/images/cafes/00062g1.jpg', '/images/cafes/00062g2.jpg', '/images/cafes/00062g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/aboutlife',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [1, 4, 5],
    koi_number: 923,
    super_koi_number: 267,
    review_ids: [67, 345, 891],
    created_at: new Date('2024-03-03')
  },
  {
    id: 63,
    slug: 'bear-pond-espresso',
    name: 'Bear Pond Espresso',
    name_ja: 'ベアポンドエスプレッソ',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Kitazawa, Setagaya-ku',
    description: 'Temple de l\'espresso artisanal, barista légendaire',
    price_range: 2,
    photos: ['/images/cafes/00063b.jpg', '/images/cafes/00063m.jpg', '/images/cafes/00063g1.jpg', '/images/cafes/00063g2.jpg', '/images/cafes/00063g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/bearpond',
    opening_days: [true, true, false, true, true, true, true],
    feature_ids: [4, 5],
    koi_number: 1456,
    super_koi_number: 456,
    review_ids: [78, 289, 654],
    created_at: new Date('2024-03-04')
  },
  {
    id: 64,
    slug: 'fuglen-tokyo',
    name: 'Fuglen Tokyo',
    name_ja: 'フグレン東京',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Tomigaya, Shibuya-ku',
    description: 'Import norvégien, café de spécialité et design scandinave',
    price_range: 2,
    photos: ['/images/cafes/00064b.jpg', '/images/cafes/00064m.jpg', '/images/cafes/00064g1.jpg', '/images/cafes/00064g2.jpg', '/images/cafes/00064g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/fuglen',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 4, 5, 7],
    koi_number: 834,
    super_koi_number: 234,
    review_ids: [56, 234, 567],
    created_at: new Date('2024-03-05')
  },
  {
    id: 65,
    slug: 'glitch-coffee-roasters',
    name: 'Glitch Coffee & Roasters',
    name_ja: 'グリッチコーヒーアンドロースターズ',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Jimbocho, Chiyoda-ku',
    description: 'Torréfaction scientifique, café third wave de précision',
    price_range: 2,
    photos: ['/images/cafes/00065b.jpg', '/images/cafes/00065m.jpg', '/images/cafes/00065g1.jpg', '/images/cafes/00065g2.jpg', '/images/cafes/00065g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/glitch',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [1, 4, 5],
    koi_number: 712,
    super_koi_number: 201,
    review_ids: [45, 178, 432],
    created_at: new Date('2024-03-06')
  },
  {
    id: 66,
    slug: 'passage-coffee',
    name: 'Passage Coffee',
    name_ja: 'パッセージコーヒー',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Sangenjaya, Setagaya-ku',
    description: 'Micro-torréfacteur, café single origin de haute volée',
    price_range: 2,
    photos: ['/images/cafes/00066b.jpg', '/images/cafes/00066m.jpg', '/images/cafes/00066g1.jpg', '/images/cafes/00066g2.jpg', '/images/cafes/00066g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/passage',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [1, 4, 5],
    koi_number: 534,
    super_koi_number: 145,
    review_ids: [34, 234],
    created_at: new Date('2024-03-07')
  },
  {
    id: 67,
    slug: 'streamer-coffee-shibuya',
    name: 'Streamer Coffee Company',
    name_ja: 'ストリーマーコーヒーカンパニー',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Shibuya, Shibuya-ku',
    description: 'Champion de latte art, café third wave et compétitions',
    price_range: 2,
    photos: ['/images/cafes/00067b.jpg', '/images/cafes/00067m.jpg', '/images/cafes/00067g1.jpg', '/images/cafes/00067g2.jpg', '/images/cafes/00067g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/streamer',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 4, 5, 7],
    koi_number: 1123,
    super_koi_number: 334,
    review_ids: [67, 289, 765],
    created_at: new Date('2024-03-08')
  },
  {
    id: 68,
    slug: 'lattest-omotesando',
    name: 'Lattest Omotesando',
    name_ja: 'ラテスト表参道',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Omotesando, Shibuya-ku',
    description: 'Café third wave design dans le quartier branché d\'Omotesando',
    price_range: 3,
    photos: ['/images/cafes/00068b.jpg', '/images/cafes/00068m.jpg', '/images/cafes/00068g1.jpg', '/images/cafes/00068g2.jpg', '/images/cafes/00068g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/lattest',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [1, 2, 4, 5],
    koi_number: 645,
    super_koi_number: 178,
    review_ids: [45, 234, 543],
    created_at: new Date('2024-03-09')
  },
  {
    id: 69,
    slug: 'the-roastery-nakameguro',
    name: 'The Roastery by Nozy Coffee',
    name_ja: 'ザロースタリーバイノージーコーヒー',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Nakameguro, Meguro-ku',
    description: 'Torréfaction transparente, café third wave éthique',
    price_range: 2,
    photos: ['/images/cafes/00069b.jpg', '/images/cafes/00069m.jpg', '/images/cafes/00069g1.jpg', '/images/cafes/00069g2.jpg', '/images/cafes/00069g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/roastery',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [1, 4, 5],
    koi_number: 789,
    super_koi_number: 223,
    review_ids: [56, 267],
    created_at: new Date('2024-03-10')
  },
  {
    id: 70,
    slug: 'leaves-coffee-shibuya',
    name: 'Leaves Coffee Apartment',
    name_ja: 'リーブスコーヒーアパートメント',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Jinnan, Shibuya-ku',
    description: 'Café third wave multi-étages, torréfaction maison',
    price_range: 2,
    photos: ['/images/cafes/00070b.jpg', '/images/cafes/00070m.jpg', '/images/cafes/00070g1.jpg', '/images/cafes/00070g2.jpg', '/images/cafes/00070g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/leaves',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [1, 4, 5, 7],
    koi_number: 867,
    super_koi_number: 245,
    review_ids: [78, 345],
    created_at: new Date('2024-03-11')
  },
  {
    id: 71,
    slug: 'koffee-mameya-omotesando',
    name: 'Koffee Mameya',
    name_ja: 'コーヒーマメヤ',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Jingumae, Shibuya-ku',
    description: 'Boutique-café third wave, sélection de grains du monde entier',
    price_range: 3,
    photos: ['/images/cafes/00071b.jpg', '/images/cafes/00071m.jpg', '/images/cafes/00071g1.jpg', '/images/cafes/00071g2.jpg', '/images/cafes/00071g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/mameya',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [4, 5, 7],
    koi_number: 1034,
    super_koi_number: 312,
    review_ids: [89, 234, 678],
    created_at: new Date('2024-03-12')
  },
  {
    id: 72,
    slug: 'nozy-coffee-nishiazabu',
    name: 'Nozy Coffee',
    name_ja: 'ノージーコーヒー',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Nishiazabu, Minato-ku',
    description: 'Café third wave avec bar à cocktails le soir',
    price_range: 2,
    photos: ['/images/cafes/00072b.jpg', '/images/cafes/00072m.jpg', '/images/cafes/00072g1.jpg', '/images/cafes/00072g2.jpg', '/images/cafes/00072g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/nozy',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [1, 4, 5],
    koi_number: 623,
    super_koi_number: 167,
    review_ids: [45, 198],
    created_at: new Date('2024-03-13')
  },
  {
    id: 73,
    slug: 'trunk-coffee-nagoya',
    name: 'Trunk Coffee',
    name_ja: 'トランクコーヒー',
    category: 'third-wave',
    city: 'Nagoya',
    address: 'Chikusa, Chikusa-ku',
    description: 'Pionnier third wave de Nagoya, torréfaction locale',
    price_range: 2,
    photos: ['/images/cafes/00073b.jpg', '/images/cafes/00073m.jpg', '/images/cafes/00073g1.jpg', '/images/cafes/00073g2.jpg', '/images/cafes/00073g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/trunk',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [1, 4, 5],
    koi_number: 756,
    super_koi_number: 212,
    review_ids: [67, 289, 543],
    created_at: new Date('2024-03-14')
  },
  {
    id: 74,
    slug: 'weekenders-coffee-kyoto',
    name: 'Weekenders Coffee',
    name_ja: 'ウィークエンダーズコーヒー',
    category: 'third-wave',
    city: 'Kyoto',
    address: 'Tominokoji, Nakagyo-ku',
    description: 'Café third wave de Kyoto, torréfaction artisanale',
    price_range: 2,
    photos: ['/images/cafes/00074b.jpg', '/images/cafes/00074m.jpg', '/images/cafes/00074g1.jpg', '/images/cafes/00074g2.jpg', '/images/cafes/00074g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/weekenders',
    opening_days: [true, true, false, true, true, true, true],
    feature_ids: [1, 4, 5],
    koi_number: 534,
    super_koi_number: 145,
    review_ids: [34, 234],
    created_at: new Date('2024-03-15')
  },
  {
    id: 75,
    slug: 'light-up-coffee-tokyo',
    name: 'Light Up Coffee',
    name_ja: 'ライトアップコーヒー',
    category: 'third-wave',
    city: 'Tokyo',
    address: 'Kichijoji, Musashino-shi',
    description: 'Micro-torréfacteur third wave, café de spécialité éthique',
    price_range: 2,
    photos: ['/images/cafes/00075b.jpg', '/images/cafes/00075m.jpg', '/images/cafes/00075g1.jpg', '/images/cafes/00075g2.jpg', '/images/cafes/00075g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/lightup',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [1, 4, 5],
    koi_number: 445,
    super_koi_number: 112,
    review_ids: [23, 167],
    created_at: new Date('2024-03-16')
  },

  // ===== COFFEE STAND (15 cafés) =====
  {
    id: 76,
    slug: 'little-nap-coffee-yoyogi',
    name: 'Little Nap Coffee Stand',
    name_ja: 'リトルナップコーヒースタンド',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Yoyogi, Shibuya-ku',
    description: 'Micro coffee stand culte de Yoyogi, ambiance vintage',
    price_range: 1,
    photos: ['/images/cafes/00076b.jpg', '/images/cafes/00076m.jpg', '/images/cafes/00076g1.jpg', '/images/cafes/00076g2.jpg', '/images/cafes/00076g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/littlenap',
    opening_days: [true, true, false, true, true, true, true],
    feature_ids: [5, 7],
    koi_number: 1345,
    super_koi_number: 412,
    review_ids: [56, 289, 765],
    created_at: new Date('2024-03-17')
  },
  {
    id: 77,
    slug: 'toranomon-koffee',
    name: 'Toranomon Koffee',
    name_ja: '虎ノ門コーヒー',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Toranomon, Minato-ku',
    description: 'Coffee stand minimaliste pour businessmen pressés',
    price_range: 1,
    photos: ['/images/cafes/00077b.jpg', '/images/cafes/00077m.jpg', '/images/cafes/00077g1.jpg', '/images/cafes/00077g2.jpg', '/images/cafes/00077g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/toranomon',
    opening_days: [false, true, true, true, true, true, false],
    feature_ids: [5, 7],
    koi_number: 623,
    super_koi_number: 145,
    review_ids: [34, 178],
    created_at: new Date('2024-03-18')
  },
  {
    id: 78,
    slug: 'koffee-mameya-kakeru',
    name: 'Koffee Mameya Kakeru',
    name_ja: 'コーヒーマメヤカケル',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Jingumae, Shibuya-ku',
    description: 'Coffee stand haut de gamme, café à emporter premium',
    price_range: 2,
    photos: ['/images/cafes/00078b.jpg', '/images/cafes/00078m.jpg', '/images/cafes/00078g1.jpg', '/images/cafes/00078g2.jpg', '/images/cafes/00078g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/kakeru',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [5, 7],
    koi_number: 934,
    super_koi_number: 278,
    review_ids: [67, 345, 678],
    created_at: new Date('2024-03-19')
  },
  {
    id: 79,
    slug: 'good-town-doughnuts',
    name: 'Good Town Doughnuts',
    name_ja: 'グッドタウンドーナツ',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Sangenjaya, Setagaya-ku',
    description: 'Coffee stand avec doughnuts artisanaux, à emporter uniquement',
    price_range: 1,
    photos: ['/images/cafes/00079b.jpg', '/images/cafes/00079m.jpg', '/images/cafes/00079g1.jpg', '/images/cafes/00079g2.jpg', '/images/cafes/00079g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/goodtown',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [5, 7],
    koi_number: 567,
    super_koi_number: 134,
    review_ids: [45, 234],
    created_at: new Date('2024-03-20')
  },
  {
    id: 80,
    slug: 'arise-coffee-shibuya',
    name: 'Arise Coffee Entangle',
    name_ja: 'アライズコーヒーエンタングル',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Shibuya, Shibuya-ku',
    description: 'Coffee stand urbain, café rapide de qualité',
    price_range: 1,
    photos: ['/images/cafes/00080b.jpg', '/images/cafes/00080m.jpg', '/images/cafes/00080g1.jpg', '/images/cafes/00080g2.jpg', '/images/cafes/00080g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/arise',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [5, 7],
    koi_number: 812,
    super_koi_number: 223,
    review_ids: [78, 345],
    created_at: new Date('2024-03-21')
  },
  {
    id: 81,
    slug: 'single-o-omotesando',
    name: 'Single O Omotesando',
    name_ja: 'シングルオー表参道',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Jingumae, Shibuya-ku',
    description: 'Import australien, flat white à emporter',
    price_range: 2,
    photos: ['/images/cafes/00081b.jpg', '/images/cafes/00081m.jpg', '/images/cafes/00081g1.jpg', '/images/cafes/00081g2.jpg', '/images/cafes/00081g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/singleo',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [5, 7],
    koi_number: 723,
    super_koi_number: 198,
    review_ids: [56, 267, 543],
    created_at: new Date('2024-03-22')
  },
  {
    id: 82,
    slug: 'coffee-supreme-harajuku',
    name: 'Coffee Supreme Tokyo',
    name_ja: 'コーヒーシュプリーム東京',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Harajuku, Shibuya-ku',
    description: 'Coffee stand néo-zélandais, service ultra-rapide',
    price_range: 1,
    photos: ['/images/cafes/00082b.jpg', '/images/cafes/00082m.jpg', '/images/cafes/00082g1.jpg', '/images/cafes/00082g2.jpg', '/images/cafes/00082g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/supreme',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [5, 7],
    koi_number: 645,
    super_koi_number: 167,
    review_ids: [34, 189],
    created_at: new Date('2024-03-23')
  },
  {
    id: 83,
    slug: 'allpress-espresso-tokyo',
    name: 'Allpress Espresso',
    name_ja: 'オールプレスエスプレッソ',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Kiyosumi-Shirakawa, Koto-ku',
    description: 'Torréfacteur néo-zélandais, coffee stand et roastery',
    price_range: 1,
    photos: ['/images/cafes/00083b.jpg', '/images/cafes/00083m.jpg', '/images/cafes/00083g1.jpg', '/images/cafes/00083g2.jpg', '/images/cafes/00083g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/allpress',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [1, 5, 7],
    koi_number: 856,
    super_koi_number: 234,
    review_ids: [67, 289, 678],
    created_at: new Date('2024-03-24')
  },
  {
    id: 84,
    slug: 'unlimited-coffee-bar',
    name: 'Unlimited Coffee Bar',
    name_ja: 'アンリミテッドコーヒーバー',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Shibuya, Shibuya-ku',
    description: 'Micro coffee stand dans une ruelle de Shibuya',
    price_range: 1,
    photos: ['/images/cafes/00084b.jpg', '/images/cafes/00084m.jpg', '/images/cafes/00084g1.jpg', '/images/cafes/00084g2.jpg', '/images/cafes/00084g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/unlimited',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [5, 7],
    koi_number: 423,
    super_koi_number: 98,
    review_ids: [23, 145],
    created_at: new Date('2024-03-25')
  },
  {
    id: 85,
    slug: 'switch-coffee-meguro',
    name: 'Switch Coffee Tokyo',
    name_ja: 'スイッチコーヒー東京',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Meguro, Meguro-ku',
    description: 'Coffee stand avec torréfaction visible, café frais',
    price_range: 1,
    photos: ['/images/cafes/00085b.jpg', '/images/cafes/00085m.jpg', '/images/cafes/00085g1.jpg', '/images/cafes/00085g2.jpg', '/images/cafes/00085g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/switch',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [5, 7],
    koi_number: 534,
    super_koi_number: 123,
    review_ids: [45, 198],
    created_at: new Date('2024-03-26')
  },
  {
    id: 86,
    slug: 'turret-coffee-sangenjaya',
    name: 'Turret Coffee',
    name_ja: 'タレットコーヒー',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Sangenjaya, Setagaya-ku',
    description: 'Petit coffee stand de quartier, clientèle locale',
    price_range: 1,
    photos: ['/images/cafes/00086b.jpg', '/images/cafes/00086m.jpg', '/images/cafes/00086g1.jpg', '/images/cafes/00086g2.jpg', '/images/cafes/00086g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/turret',
    opening_days: [true, true, false, true, true, true, true],
    feature_ids: [5, 7],
    koi_number: 312,
    super_koi_number: 78,
    review_ids: [34, 156],
    created_at: new Date('2024-03-27')
  },
  {
    id: 87,
    slug: 'be-a-good-neighbor-daikanyama',
    name: 'BE A GOOD NEIGHBOR',
    name_ja: 'ビーアグッドネイバー',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Daikanyama, Shibuya-ku',
    description: 'Coffee stand design, café et vêtements vintage',
    price_range: 1,
    photos: ['/images/cafes/00087b.jpg', '/images/cafes/00087m.jpg', '/images/cafes/00087g1.jpg', '/images/cafes/00087g2.jpg', '/images/cafes/00087g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/bagn',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [5, 7],
    koi_number: 678,
    super_koi_number: 189,
    review_ids: [56, 234, 432],
    created_at: new Date('2024-03-28')
  },
  {
    id: 88,
    slug: 'coffee-wrights-sangenjaya',
    name: 'Coffee Wrights',
    name_ja: 'コーヒーライツ',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Sangenjaya, Setagaya-ku',
    description: 'Micro-torréfacteur et coffee stand artisanal',
    price_range: 1,
    photos: ['/images/cafes/00088b.jpg', '/images/cafes/00088m.jpg', '/images/cafes/00088g1.jpg', '/images/cafes/00088g2.jpg', '/images/cafes/00088g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/wrights',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [5, 7],
    koi_number: 445,
    super_koi_number: 112,
    review_ids: [23, 167],
    created_at: new Date('2024-03-29')
  },
  {
    id: 89,
    slug: 'coffee-den-jimbocho',
    name: 'Coffee Den',
    name_ja: 'コーヒー伝',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Jimbocho, Chiyoda-ku',
    description: 'Coffee stand caché dans le quartier des livres',
    price_range: 1,
    photos: ['/images/cafes/00089b.jpg', '/images/cafes/00089m.jpg', '/images/cafes/00089g1.jpg', '/images/cafes/00089g2.jpg', '/images/cafes/00089g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/den',
    opening_days: [false, true, true, true, true, true, false],
    feature_ids: [5, 7],
    koi_number: 389,
    super_koi_number: 87,
    review_ids: [45, 189],
    created_at: new Date('2024-03-30')
  },
  {
    id: 90,
    slug: 'berth-coffee-roasters',
    name: 'Berth Coffee Roasters',
    name_ja: 'バースコーヒーロースターズ',
    category: 'coffee-stand',
    city: 'Tokyo',
    address: 'Kiyosumi, Koto-ku',
    description: 'Coffee stand dans une ancienne usine rénovée',
    price_range: 1,
    photos: ['/images/cafes/00090b.jpg', '/images/cafes/00090m.jpg', '/images/cafes/00090g1.jpg', '/images/cafes/00090g2.jpg', '/images/cafes/00090g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/berth',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [1, 5, 7],
    koi_number: 567,
    super_koi_number: 145,
    review_ids: [67, 234],
    created_at: new Date('2024-03-31')
  },

  // ===== ONSEN CAFE (15 cafés) =====
  {
    id: 91,
    slug: 'onsen-ryokan-yuen-shinjuku',
    name: 'Onsen Ryokan Yuen Shinjuku',
    name_ja: '温泉旅館由縁新宿',
    category: 'onsen-cafe',
    city: 'Tokyo',
    address: 'Shinjuku, Shinjuku-ku',
    description: 'Onsen urbain avec salon de thé traditionnel, détente complète',
    price_range: 3,
    photos: ['/images/cafes/00091b.jpg', '/images/cafes/00091m.jpg', '/images/cafes/00091g1.jpg', '/images/cafes/00091g2.jpg', '/images/cafes/00091g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/yuen',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 3, 5, 10],
    koi_number: 1234,
    super_koi_number: 378,
    review_ids: [56, 289, 765],
    created_at: new Date('2024-04-01')
  },
  {
    id: 92,
    slug: 'thermae-yu-yokohama',
    name: 'Thermae-Yu',
    name_ja: 'テルマー湯',
    category: 'onsen-cafe',
    city: 'Yokohama',
    address: 'Minato Mirai, Nishi-ku',
    description: 'Complexe onsen avec café-restaurant, vue sur la baie',
    price_range: 3,
    photos: ['/images/cafes/00092b.jpg', '/images/cafes/00092m.jpg', '/images/cafes/00092g1.jpg', '/images/cafes/00092g2.jpg', '/images/cafes/00092g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/thermae',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 2, 5, 10],
    koi_number: 1567,
    super_koi_number: 456,
    review_ids: [78, 345, 891],
    created_at: new Date('2024-04-02')
  },
  {
    id: 93,
    slug: 'oedo-onsen-odaiba',
    name: 'Oedo Onsen Monogatari',
    name_ja: '大江戸温泉物語',
    category: 'onsen-cafe',
    city: 'Tokyo',
    address: 'Odaiba, Koto-ku',
    description: 'Village onsen avec multiples cafés et restaurants thématiques',
    price_range: 2,
    photos: ['/images/cafes/00093b.jpg', '/images/cafes/00093m.jpg', '/images/cafes/00093g1.jpg', '/images/cafes/00093g2.jpg', '/images/cafes/00093g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/oedo',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 2, 4, 5, 10],
    koi_number: 2134,
    super_koi_number: 634,
    review_ids: [89, 234, 678, 912],
    created_at: new Date('2024-04-03')
  },
  {
    id: 94,
    slug: 'spa-laqua-tokyo-dome',
    name: 'Spa LaQua',
    name_ja: 'スパラクーア',
    category: 'onsen-cafe',
    city: 'Tokyo',
    address: 'Koraku, Bunkyo-ku',
    description: 'Spa onsen avec cafés et restaurants, complexe Tokyo Dome City',
    price_range: 3,
    photos: ['/images/cafes/00094b.jpg', '/images/cafes/00094m.jpg', '/images/cafes/00094g1.jpg', '/images/cafes/00094g2.jpg', '/images/cafes/00094g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/laqua',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [1, 2, 4, 5, 10],
    koi_number: 1823,
    super_koi_number: 512,
    review_ids: [67, 289, 745],
    created_at: new Date('2024-04-04')
  },
  {
    id: 95,
    slug: 'gora-kadan-hakone',
    name: 'Gora Kadan',
    name_ja: '強羅花壇',
    category: 'onsen-cafe',
    city: 'Hakone',
    address: 'Gora, Hakone-machi',
    description: 'Ryokan de luxe avec salon de thé, sources thermales privées',
    price_range: 3,
    photos: ['/images/cafes/00095b.jpg', '/images/cafes/00095m.jpg', '/images/cafes/00095g1.jpg', '/images/cafes/00095g2.jpg', '/images/cafes/00095g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/gorakadan',
    opening_days: [true, true, true, true, true, true, true],
    feature_ids: [3, 5, 9, 10],
    koi_number: 923,
    super_koi_number: 287,
    review_ids: [45, 234, 567],
    created_at: new Date('2024-04-05')
  },
  {
    id: 96,
    slug: 'kusatsu-onsen-cafe',
    name: 'Kusatsu Onsen Café',
    name_ja: '草津温泉カフェ',
    category: 'onsen-cafe',
    city: 'Kusatsu',
    address: 'Kusatsu-machi, Agatsuma-gun',
    description: 'Café dans la ville thermale historique de Kusatsu',
    price_range: 2,
    photos: ['/images/cafes/00096b.jpg', '/images/cafes/00096m.jpg', '/images/cafes/00096g1.jpg', '/images/cafes/00096g2.jpg', '/images/cafes/00096g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/kusatsu',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [1, 5, 9, 10],
    koi_number: 756,
    super_koi_number: 212,
    review_ids: [56, 267, 543],
    created_at: new Date('2024-04-06')
  },
  {
    id: 97,
    slug: 'kinosaki-onsen-cafe',
    name: 'Kinosaki Onsen Café',
    name_ja: '城崎温泉カフェ',
    category: 'onsen-cafe',
    city: 'Toyooka',
    address: 'Kinosaki-cho, Toyooka-shi',
    description: 'Café traditionnel dans la ville onsen de Kinosaki',
    price_range: 2,
    photos: ['/images/cafes/00097b.jpg', '/images/cafes/00097m.jpg', '/images/cafes/00097g1.jpg', '/images/cafes/00097g2.jpg', '/images/cafes/00097g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/kinosaki',
    opening_days: [true, true, false, true, true, true, true],
    feature_ids: [1, 3, 5, 10],
    koi_number: 634,
    super_koi_number: 178,
    review_ids: [34, 189, 432],
    created_at: new Date('2024-04-07')
  },
  {
    id: 98,
    slug: 'arima-onsen-teahouse',
    name: 'Arima Onsen Teahouse',
    name_ja: '有馬温泉茶房',
    category: 'onsen-cafe',
    city: 'Kobe',
    address: 'Arima-cho, Kita-ku',
    description: 'Salon de thé dans la ville thermale d\'Arima',
    price_range: 2,
    photos: ['/images/cafes/00098b.jpg', '/images/cafes/00098m.jpg', '/images/cafes/00098g1.jpg', '/images/cafes/00098g2.jpg', '/images/cafes/00098g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/arima',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [3, 5, 9, 10],
    koi_number: 512,
    super_koi_number: 134,
    review_ids: [45, 234],
    created_at: new Date('2024-04-08')
  },
  {
    id: 99,
    slug: 'beppu-onsen-lounge',
    name: 'Beppu Onsen Lounge',
    name_ja: '別府温泉ラウンジ',
    category: 'onsen-cafe',
    city: 'Beppu',
    address: 'Kitahama, Beppu-shi',
    description: 'Lounge café avec vue sur la baie de Beppu, onsen à proximité',
    price_range: 2,
    photos: ['/images/cafes/00099b.jpg', '/images/cafes/00099m.jpg', '/images/cafes/00099g1.jpg', '/images/cafes/00099g2.jpg', '/images/cafes/00099g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/beppu',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [1, 5, 9, 10],
    koi_number: 867,
    super_koi_number: 245,
    review_ids: [67, 289, 654],
    created_at: new Date('2024-04-09')
  },
  {
    id: 100,
    slug: 'noboribetsu-onsen-cafe',
    name: 'Noboribetsu Onsen Café',
    name_ja: '登別温泉カフェ',
    category: 'onsen-cafe',
    city: 'Noboribetsu',
    address: 'Noboribetsu-onsen-cho',
    description: 'Café dans la ville thermale volcanique d\'Hokkaido',
    price_range: 2,
    photos: ['/images/cafes/00100b.jpg', '/images/cafes/00100m.jpg', '/images/cafes/00100g1.jpg', '/images/cafes/00100g2.jpg', '/images/cafes/00100g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/noboribetsu',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [1, 5, 9, 10],
    koi_number: 445,
    super_koi_number: 112,
    review_ids: [23, 156],
    created_at: new Date('2024-04-10')
  },
  {
    id: 101,
    slug: 'yufuin-onsen-gallery-cafe',
    name: 'Yufuin Onsen Gallery Café',
    name_ja: '由布院温泉ギャラリーカフェ',
    category: 'onsen-cafe',
    city: 'Yufu',
    address: 'Yufuin-cho, Yufu-shi',
    description: 'Café-galerie avec vue sur le Mont Yufu, onsen artistique',
    price_range: 2,
    photos: ['/images/cafes/00101b.jpg', '/images/cafes/00101m.jpg', '/images/cafes/00101g1.jpg', '/images/cafes/00101g2.jpg', '/images/cafes/00101g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/yufuin',
    opening_days: [true, true, true, false, true, true, true],
    feature_ids: [2, 5, 8, 9, 10],
    koi_number: 723,
    super_koi_number: 201,
    review_ids: [56, 267, 543],
    created_at: new Date('2024-04-11')
  },
  {
    id: 102,
    slug: 'dogo-onsen-teahouse',
    name: 'Dogo Onsen Teahouse',
    name_ja: '道後温泉茶房',
    category: 'onsen-cafe',
    city: 'Matsuyama',
    address: 'Dogo-himezuka, Matsuyama-shi',
    description: 'Salon de thé près du plus ancien onsen public du Japon',
    price_range: 2,
    photos: ['/images/cafes/00102b.jpg', '/images/cafes/00102m.jpg', '/images/cafes/00102g1.jpg', '/images/cafes/00102g2.jpg', '/images/cafes/00102g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/dogo',
    opening_days: [true, true, false, true, true, true, true],
    feature_ids: [3, 5, 6, 10],
    koi_number: 956,
    super_koi_number: 278,
    review_ids: [78, 345, 678],
    created_at: new Date('2024-04-12')
  },
  {
    id: 103,
    slug: 'kurokawa-onsen-cafe',
    name: 'Kurokawa Onsen Café',
    name_ja: '黒川温泉カフェ',
    category: 'onsen-cafe',
    city: 'Minamioguni',
    address: 'Manganji, Minamioguni-machi',
    description: 'Café rustique dans le village onsen caché de Kurokawa',
    price_range: 2,
    photos: ['/images/cafes/00103b.jpg', '/images/cafes/00103m.jpg', '/images/cafes/00103g1.jpg', '/images/cafes/00103g2.jpg', '/images/cafes/00103g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/kurokawa',
    opening_days: [true, false, true, true, true, true, true],
    feature_ids: [1, 5, 9, 10],
    koi_number: 534,
    super_koi_number: 145,
    review_ids: [34, 189],
    created_at: new Date('2024-04-13')
  },
  {
    id: 104,
    slug: 'takaragawa-onsen-lounge',
    name: 'Takaragawa Onsen Lounge',
    name_ja: '宝川温泉ラウンジ',
    category: 'onsen-cafe',
    city: 'Minakami',
    address: 'Fujiwara, Minakami-machi',
    description: 'Lounge avec vue sur la rivière, rotenburo géant à proximité',
    price_range: 2,
    photos: ['/images/cafes/00104b.jpg', '/images/cafes/00104m.jpg', '/images/cafes/00104g1.jpg', '/images/cafes/00104g2.jpg', '/images/cafes/00104g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/takaragawa',
    opening_days: [true, true, true, true, true, true, false],
    feature_ids: [1, 5, 9, 10],
    koi_number: 423,
    super_koi_number: 98,
    review_ids: [45, 234],
    created_at: new Date('2024-04-14')
  },
  {
    id: 105,
    slug: 'shirahone-onsen-cafe',
    name: 'Shirahone Onsen Café',
    name_ja: '白骨温泉カフェ',
    category: 'onsen-cafe',
    city: 'Matsumoto',
    address: 'Azumi, Matsumoto-shi',
    description: 'Café dans le village onsen alpin de Shirahone',
    price_range: 2,
    photos: ['/images/cafes/00105b.jpg', '/images/cafes/00105m.jpg', '/images/cafes/00105g1.jpg', '/images/cafes/00105g2.jpg', '/images/cafes/00105g3.jpg'],
    google_maps_url: 'https://maps.app.goo.gl/shirahone',
    opening_days: [false, true, true, true, true, true, true],
    feature_ids: [1, 5, 9, 10],
    koi_number: 312,
    super_koi_number: 78,
    review_ids: [23, 167],
    created_at: new Date('2024-04-15')
  }
]

export function getAllCafes(): Cafe[] {
  return cafes
}

export function getCafeBySlug(slug: string): Cafe | undefined {
  return cafes.find(cafe => cafe.slug === slug)
}

export function getCafesByCategory(categorySlug: string): Cafe[] {
  return cafes.filter(cafe => cafe.category === categorySlug)
}

export function getCafeById(id: number): Cafe | undefined {
  return cafes.find(cafe => cafe.id === id)
}